### PR TITLE
Table of available languages

### PR DESCRIPTION
**Pull request by tinthenet**

### CODE REVIEW

**Comment by tinthenet** [comment]
Maybe the % column is not necessary

**Comment by tinthenet** [comment]
@franzdumfart I can add the detailed Country details but I don't know which LCID String correspond to the created translate. For example, the AR for Arabic have 16 LCID String.

**Comment by franzdumfart** [comment]
@tinthenet Sure. I would only add this details on countries with multiple versions. In our case `nb_NO`, `pt_BR` and `zh_CN`. More will follow for sure, but this should do it for now.

**Comment by franzdumfart** [comment]
Just great, thanks so much!!!

**Pull request merged**
